import { Data } from './data-type';

export const DATA: Data[] = [
  { id: 1, 
  	name: 'Therapy Department', 
    link: 'Therapy',
  	url: './assets/units_foto/therapy_department.jpg',
  	patient: [
 	{ 	name: 'Anna Schmidt',
  	  dx: 'Grippe', 
  		date: '2019-10-20T09:30:00.000Z',
      staff: 'Katrin Sommer', 
      position: 'Doctor',
  		age: 30, 
  		sex: 'Mrs', 
  		adress: 'Friedrich-Schmidt-Platz 0, 1010 Wien', 
  		foto: './assets/patients_foto/patien1.png', 
      task_number: 341,
      task__description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      task__status: 'execution',
      tasks: [
        {task_code: 'DIAG01', 
        name: 'Heart rate check',    
        timein: '2019-11-10T16:51:50.969Z', 
        timeout: '2019-11-10T17:01:50.969Z',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        staff: "Gabriele Huber", 
        position: 'GHS'
        },
        {task_code: 'DIAG02', 
        name: 'Therapy and treatment',     
        timein: '2019-11-10T14:51:50.969Z', 
        timeout: '2019-12-21T15:51:50.969Z', 
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        staff: 'Kerstin Gruber', 
        position: 'Doctor'
        },
        {task_code: 'DIAG03', 
        name: 'Blood pressure control',     
        timein: '2019-12-21T15:31:50.969Z', 
        timeout: '2019-12-21T15:40:50.969Z', 
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        staff: "Dominik Schwarz", 
        position: 'Care assistant'
        }  
      ]
  	},
  	{	name: 'Hannah Smith', 
  		dx: 'Hypertonische Krisen', 
  		date: "2019-09-19T12:40:00.000Z",
  		age: 55, 
  		sex: "Mrs", 
  		adress: 'Sudirman Street 0, 10110 Jakarta', 
  		foto: './assets/patients_foto/patient2.jpg', 
      staff: "Tanja Fuchs", 
      position: 'Doctor',
      task_number: 342,
      task__description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
      task__status: 'execution',
      tasks: [
        {task_code: 'DIAG02', 
        name: 'Heart rate check',    
        timein: '2019-09-01T16:51:50.969Z', 
        timeout: '2019-09-01T17:01:50.969Z',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        staff: "Dominik Huber", 
        position: 'GHS'
        },
        {task_code: 'DIAG02', 
        name: 'Therapy and treatment',     
        timein: '2019-11-10T14:51:50.969Z', 
        timeout: '2019-12-21T15:51:50.969Z', 
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        staff: 'Kerstin Gruber', 
        position: 'Doctor'
        },
        {task_code: 'TBV01', 
        name: 'Blood pressure control',     
        timein: '2019-09-21T15:31:50.969Z', 
        timeout: '2019-09-21T15:40:50.969Z', 
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        staff: "Ulrich Krenn", 
        position: 'Care assistant'
        }  
      ]
    },
    { name: 'Christina Johnson', 
  		dx: 'Myokardinfarkt', 
  		date: "2019-11-16T15:45:00.000Z",
      staff: "Katrin Sommer", 
      position: 'Doctor',
  		age: 80, 
  		sex: "Mrs", 
  		adress: 'Paranthe Wali Gali 0, 110001 Delhi', 
  		foto: './assets/patients_foto/patient3.jpg', 
      task_number: 343,
      task__description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
      task__status: 'execution',
      tasks: [
        {task_code: 'DIAG02', 
        name: 'Heart rate check',    
        timein: '2019-09-01T16:51:50.969Z', 
        timeout: '2019-09-01T17:01:50.969Z',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        staff: "Dominik Huber", 
        position: 'GHS'
        },
        {task_code: 'DIAG02', 
        name: 'Therapy and treatment',     
        timein: '2019-11-10T14:51:50.969Z', 
        timeout: '2019-12-21T15:51:50.969Z', 
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        staff: 'Katrin Sommer', 
        position: 'Doctor'
        },
        {task_code: 'TBV01', 
        name: 'Blood pressure control',     
        timein: '2019-09-21T15:31:50.969Z', 
        timeout: '2019-09-21T15:40:50.969Z', 
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        staff: "Ulrich Krenn", 
        position: 'Care assistant'
        }  
      ]
    },
    { name: 'Christian Williams', 
  		dx: 'Bronchialasthma', 
  		date: "2019-11-22T05:00:00.000Z", 
      staff: "Dominik Schwarz", 
      position: 'Care assistant',
  		age: 25, 
  		sex: "Mrs", 
  		adress: 'Folgueras Street 0, 1000 Manila', 
  		foto: './assets/patients_foto/patient4.jpg', 
      task_number: 344,
      task__description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
      task__status: 'execution',
      tasks: [
        {task_code: 'DIAG02', 
        name: 'Heart rate check',    
        timein: '2019-09-01T16:51:50.969Z', 
        timeout: '2019-09-01T17:01:50.969Z',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        staff: "Dominik Huber", 
        position: 'GHS'
        },
        {task_code: 'DIAG02', 
        name: 'Therapy and treatment',     
        timein: '2019-11-10T14:51:50.969Z', 
        timeout: '2019-12-21T15:51:50.969Z', 
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        staff: 'Katrin Sommer', 
        position: 'Doctor'
        },
        {task_code: 'TBV01', 
        name: 'Blood pressure control',     
        timein: '2019-09-21T15:31:50.969Z', 
        timeout: '2019-09-21T15:40:50.969Z', 
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        staff: "Ulrich Krenn", 
        position: 'Care assistant'
        }  
      ]
    },
    { name: 'Paul Jones', 
  		dx: 'Osteoarthrose', 
  		date: "2019-11-21T11:20:00.000Z", 
      staff: 'Ulrich Krenn', 
      position: 'GHS',
  		age: 31, 
  		sex: "Mr", 
  		adress: 'Myeongdong 0, 100011 Seoul', 
  		foto: './assets/patients_foto/patient5.jpg'},
    { name: 'Michelle Schulze', 
  		dx: 'Chronische myeloische Leukämie', 
  		date: "2019-11-20T10:05:00.000Z",
      staff: 'Kerstin Gruber', 
      position: 'Doctor',
  		age: 70, 
  		sex: "Mr", 
  		adress: 'Yuyuan Old Street  0, 200000 Shanghai', 
  		foto: './assets/patients_foto/patient6.jpg', 
      task_number: 345,
      task__description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
      task__status: 'execution',
      tasks: [
        {task_code: 'DIAG02', 
        name: 'Heart rate check',    
        timein: '2019-09-01T16:51:50.969Z', 
        timeout: '2019-09-01T17:01:50.969Z',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        staff: "Dominik Huber", 
        position: 'GHS'
        },
        {task_code: 'DIAG02', 
        name: 'Therapy and treatment',     
        timein: '2019-11-10T14:51:50.969Z', 
        timeout: '2019-12-21T15:51:50.969Z', 
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        staff: 'Katrin Sommer', 
        position: 'Doctor'
        },
        {task_code: 'TBV01', 
        name: 'Blood pressure control',     
        timein: '2019-09-21T15:31:50.969Z', 
        timeout: '2019-09-21T15:40:50.969Z', 
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        staff: "Ulrich Krenn", 
        position: 'Care assistant'
        }  
      ]
    }
  	] },
  { id: 2, 
  	name: 'Surgery Department', 
    link: 'Surgery',
  	url: './assets/units_foto/surgery_department.jpg',
  	patient: [
  	{	name: 'Hannah Smith', 
  		dx: 'Hypertonische Krisen', 
  		date: "2019-11-19T12:40:00.000Z",
      staff: 'Kerstin Gruber', 
      position: 'Doctor',
  		age: 55, 
  		sex: "Mrs", 
  		adress: 'Sudirman Street 0, 10110 Jakarta', 
  		foto: './assets/patients_foto/patient2.jpg', },
    { 	name: 'Christina Johnson', 
  		dx: 'Myokardinfarkt', 
  		date: "2019-11-16T15:45:00.000Z",
      staff: "Katrin Sommer", 
      position: 'Doctor',
  		age: 80, 
  		sex: "Mrs", 
  		adress: 'Paranthe Wali Gali 0, 110001 Delhi', 
  		foto: './assets/patients_foto/patient3.jpg', },
    { 	name: 'Christian Williams', 
  		dx: 'Bronchialasthma', 
  		date: "2019-11-22T05:00:00.000Z", 
      staff: "Katrin Sommer", 
      position: 'Doctor',
  		age: 25, 
  		sex: "Mrs", 
  		adress: 'Folgueras Street 0, 1000 Manila', 
  		foto: './assets/patients_foto/patient4.jpg', },    
    { 	name: 'Michelle Schulze', 
  		dx: 'Chronische myeloische Leukämie', 
  		date: "2019-11-20T10:05:00.000Z",
      staff: "Katrin Sommer", 
      position: 'Doctor',
  		age: 70, 
  		sex: "Mr", 
  		adress: 'Yuyuan Old Street  0, 200000 Shanghai', 
  		foto: './assets/patients_foto/patient6.jpg', }
  	]   },
  { id: 3, 
  	name: 'Clinic of Neurology', 
    link: 'Neurology',
  	url: './assets/units_foto/clinic_of_neurology.jpg',
  	patient: [
    { 	name: 'Christina Johnson', 
  		dx: 'Myokardinfarkt', 
  		date: "2019-11-16T15:45:00.000Z",
      staff: "Katrin Sommer", 
      position: 'Doctor',
  		age: 80, 
  		sex: "Mrs", 
  		adress: 'Paranthe Wali Gali 0, 110001 Delhi', 
  		foto: '../assets/patients_foto/patient3.jpg', },
    { 	name: 'Christian Williams', 
  		dx: 'Bronchialasthma', 
  		date: "2019-11-22T05:00:00.000Z", 
      staff: "Tanja Fuchs", 
      position: 'Doctor',
  		age: 25, 
  		sex: "Mrs", 
  		adress: 'Folgueras Street 0, 1000 Manila', 
  		foto: './assets/patients_foto/patient4.jpg', },
    { 	name: 'Paul Jones', 
  		dx: 'Osteoarthrose', 
  		date: "2019-11-21T11:20:00.000Z", 
      staff: "Tanja Fuchs", 
      position: 'Doctor',
  		age: 31, 
  		sex: "Mr", 
  		adress: 'Myeongdong 0, 100011 Seoul', 
  		foto: './assets/patients_foto/patient5.jpg'},
    { 	name: 'Michelle Schulze', 
  		dx: 'Chronische myeloische Leukämie', 
  		date: "2019-11-20T10:05:00.000Z",
      staff: "Tanja Fuchs", 
      position: 'Doctor',
  		age: 70, 
  		sex: "Mr", 
  		adress: 'Yuyuan Old Street  0, 200000 Shanghai', 
  		foto: './assets/patients_foto/patient6.jpg', }
  	]   },
  { id: 4, 
  	name: 'Cardiology Department', 
    link: 'Cardiology',
  	url: './assets/units_foto/cardiology_department.jpg',
  	patient: [
    { 	name: 'Christian Williams', 
  		dx: 'Bronchialasthma', 
  		date: "2019-11-22T05:00:00.000Z", 
      staff: "Tanja Fuchs", 
      position: 'Doctor',
  		age: 25, 
  		sex: "Mrs", 
  		adress: 'Folgueras Street 0, 1000 Manila', 
  		foto: './assets/patients_foto/patient4.jpg', },
    { 	name: 'Paul Jones', 
  		dx: 'Osteoarthrose', 
  		date: "2019-11-21T11:20:00.000Z", 
      staff: "Katrin Sommer", 
      position: 'Doctor',
  		age: 31, 
  		sex: "Mr", 
  		adress: 'Myeongdong 0, 100011 Seoul', 
  		foto: '../assets/patients_foto/patient5.jpg'},
    { 	name: 'Michelle Schulze', 
  		dx: 'Chronische myeloische Leukämie', 
  		date: "2019-11-20T10:05:00.000Z",
      staff: "Katrin Sommer", 
      position: 'Doctor',
  		age: 70, 
  		sex: "Mr", 
  		adress: 'Yuyuan Old Street  0, 200000 Shanghai', 
  		foto: './assets/patients_foto/patient6.jpg', }
  	]   },
  { id: 5, 
  	name: 'Department of Gastroenterology', 
    link: 'Gastroenterology',
  	url: './assets/units_foto/department_of_gastroenterology.jpg',
  	patient: [
    { 	name: 'Paul Jones', 
  		dx: 'Osteoarthrose', 
  		date: "2019-11-21T11:20:00.000Z", 
      staff: "Katrin Sommer", 
      position: 'Doctor',
  		age: 31, 
  		sex: "Mr", 
  		adress: 'Myeongdong 0, 100011 Seoul', 
  		foto: './assets/patients_foto/patient5.jpg'},
    { 	name: 'Michelle Schulze', 
  		dx: 'Chronische myeloische Leukämie', 
  		date: "2019-11-20T10:05:00.000Z",
      staff: "Dominik Schwarz", 
      position: 'Care assistant',
  		age: 70, 
  		sex: "Mr", 
  		adress: 'Yuyuan Old Street  0, 200000 Shanghai', 
  		foto: './assets/patients_foto/patient6.jpg', }
  	]   },
  { id: 6, 
  	name: 'Allergy Department', 
    link: 'Allergy',
  	url: './assets/units_foto/allergy_department.jpg',
  	patient: [
    { 	name: 'Michelle Schulze', 
  		dx: 'Chronische myeloische Leukämie', 
  		date: "2019-11-20T10:05:00.000Z",
      staff: "Katrin Sommer", 
      position: 'Doctor',
  		age: 70, 
  		sex: "Mr", 
  		adress: 'Yuyuan Old Street  0, 200000 Shanghai', 
  		foto: './assets/patients_foto/patient6.jpg', }
  	]   }
];
